# Generated by Django 2.2 on 2019-03-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supeHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city_or_origin', models.CharField(max_length=40)),
                ('dropdown', models.CharField(max_length=35)),
                ('dropdown2', models.CharField(max_length=35)),
                ('dropdown3', models.CharField(max_length=35)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
